<a href="https://colab.research.google.com/github/elyesboujelben1/gomycode/blob/main/checkpoint9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
dataset = [['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],

        ['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],

        ['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],

        ['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],

      ['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']]
dataset

[['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],
 ['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],
 ['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],
 ['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],
 ['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']]

In [92]:
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)    #Apply one-hot-encoding on our dataset
df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array
df

   Dress  Earrings    Hat  Heels  ...  Shirt  Skirt  Sneakers  Sunglasses
0  False     False   True  False  ...  False   True      True       False
1  False     False   True  False  ...  False   True      True        True
2   True     False  False   True  ...  False  False     False       False
3   True      True   True   True  ...  False  False     False       False
4  False      True  False  False  ...   True   True     False       False

[5 rows x 12 columns]

In [93]:
from mlxtend.frequent_patterns import apriori
apriori(df, min_support=0.6)

   support itemsets
0      0.6      (2)
1      0.8      (5)
2      0.8      (7)
3      0.6      (9)
4      0.6   (5, 7)
5      0.6   (9, 5)

In [94]:
frequent_itemsets=apriori(df, min_support=0.6, use_colnames=True) #Instead of column indices we can use column names.
frequent_itemsets

   support        itemsets
0      0.6           (Hat)
1      0.8         (Pants)
2      0.8         (Scarf)
3      0.6         (Skirt)
4      0.6  (Pants, Scarf)
5      0.6  (Pants, Skirt)

these items/itemsets appear each at 60% of transactions so they are the most bought as the seller must focus on them

In [95]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7) # associate itemsets with confidence over 70%.

  antecedents consequents  antecedent support  ...    lift  leverage  conviction
0     (Pants)     (Scarf)                 0.8  ...  0.9375     -0.04         0.8
1     (Scarf)     (Pants)                 0.8  ...  0.9375     -0.04         0.8
2     (Pants)     (Skirt)                 0.8  ...  1.2500      0.12         1.6
3     (Skirt)     (Pants)                 0.6  ...  1.2500      0.12         inf

[4 rows x 9 columns]

skirts are always bought with pants
as when buying pants, there is 0.75 chance the buyer will get skirt and/or scarf
when buying scarf , there is 0.75 chance the buyer will get pants

In [96]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="lift",min_threshold=1.25)

  antecedents consequents  antecedent support  ...  lift  leverage  conviction
0     (Skirt)     (Pants)                 0.6  ...  1.25      0.12         inf

[1 rows x 9 columns]

Here, the lift is bigger than 1 so there is a bigger chance skirt and pants are bought toghether than buying skirt alone

In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
import math
dataset = pd.read_csv("Market_Basket_Optimisation.csv",header= None)

dataset

                 0                  1   ...       18         19
0            shrimp            almonds  ...  spinach  olive oil
1           burgers          meatballs  ...      NaN        NaN
2           chutney                NaN  ...      NaN        NaN
3            turkey            avocado  ...      NaN        NaN
4     mineral water               milk  ...      NaN        NaN
...             ...                ...  ...      ...        ...
7496         butter         light mayo  ...      NaN        NaN
7497        burgers  frozen vegetables  ...      NaN        NaN
7498        chicken                NaN  ...      NaN        NaN
7499       escalope          green tea  ...      NaN        NaN
7500           eggs    frozen smoothie  ...      NaN        NaN

[7501 rows x 20 columns]

In [ ]:
liste = []
for i in range(0, 7501):
    liste.append([str(dataset.values[i,j]) for j in range(0, 20)])
liste

In [ ]:
liste[2].remove("nan")
liste[2].count("nan")
for x in range(len(liste)):
  while liste[x].count("nan")>0:
    liste[x].remove("nan")
liste

In [100]:
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(liste).transform(liste)    #Apply one-hot-encoding on our dataset
df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array
df

       asparagus  almonds  antioxydant juice  ...   yams  yogurt cake  zucchini
0          False     True               True  ...   True        False     False
1          False    False              False  ...  False        False     False
2          False    False              False  ...  False        False     False
3          False    False              False  ...  False        False     False
4          False    False              False  ...  False        False     False
...          ...      ...                ...  ...    ...          ...       ...
7496       False    False              False  ...  False        False     False
7497       False    False              False  ...  False        False     False
7498       False    False              False  ...  False        False     False
7499       False    False              False  ...  False        False     False
7500       False    False              False  ...  False         True     False

[7501 rows x 120 columns]

In [111]:
from mlxtend.frequent_patterns import apriori
apriori(df, min_support=0.03)

     support   itemsets
0   0.033329        (4)
1   0.033729       (12)
2   0.087188       (15)
3   0.030129       (16)
4   0.081056       (17)
5   0.046794       (22)
6   0.059992       (23)
7   0.163845       (25)
8   0.080389       (30)
9   0.051060       (31)
10  0.031862       (33)
11  0.179709       (37)
12  0.079323       (40)
13  0.170911       (43)
14  0.043061       (45)
15  0.063325       (48)
16  0.095321       (49)
17  0.052393       (51)
18  0.132116       (54)
19  0.098254       (55)
20  0.049460       (59)
21  0.047460       (60)
22  0.032396       (61)
23  0.076523       (65)
24  0.129583       (71)
25  0.238368       (72)
26  0.065858       (81)
27  0.095054       (82)
28  0.042528       (92)
29  0.071457       (97)
30  0.050527       (99)
31  0.174110      (100)
32  0.030396      (106)
33  0.068391      (108)
34  0.062525      (110)
35  0.058526      (116)
36  0.033196   (25, 37)
37  0.034395   (25, 43)
38  0.032129   (25, 71)
39  0.052660   (72, 25)
40  0.039195  (25, 100)
41  0.036395   (43, 37)
42  0.030796   (37, 71)
43  0.050927   (72, 37)
44  0.036528  (100, 37)
45  0.033729   (72, 43)
46  0.035729   (72, 49)
47  0.031063   (72, 54)
48  0.040928   (72, 55)
49  0.039195  (100, 55)
50  0.047994   (72, 71)
51  0.035462  (100, 71)
52  0.033729   (72, 82)
53  0.059725  (72, 100)

In [113]:
frequent_itemsets=apriori(df, min_support=0.03, use_colnames=True) #Instead of column indices we can use column names.
frequent_itemsets

     support                            itemsets
0   0.033329                           (avocado)
1   0.033729                          (brownies)
2   0.087188                           (burgers)
3   0.030129                            (butter)
4   0.081056                              (cake)
5   0.046794                         (champagne)
6   0.059992                           (chicken)
7   0.163845                         (chocolate)
8   0.080389                           (cookies)
9   0.051060                       (cooking oil)
10  0.031862                    (cottage cheese)
11  0.179709                              (eggs)
12  0.079323                          (escalope)
13  0.170911                      (french fries)
14  0.043061                       (fresh bread)
15  0.063325                   (frozen smoothie)
16  0.095321                 (frozen vegetables)
17  0.052393                     (grated cheese)
18  0.132116                         (green tea)
19  0.098254                       (ground beef)
20  0.049460                     (herb & pepper)
21  0.047460                             (honey)
22  0.032396                          (hot dogs)
23  0.076523                    (low fat yogurt)
24  0.129583                              (milk)
25  0.238368                     (mineral water)
26  0.065858                         (olive oil)
27  0.095054                          (pancakes)
28  0.042528                            (salmon)
29  0.071457                            (shrimp)
30  0.050527                              (soup)
31  0.174110                         (spaghetti)
32  0.030396                      (tomato juice)
33  0.068391                          (tomatoes)
34  0.062525                            (turkey)
35  0.058526                  (whole wheat rice)
36  0.033196                   (chocolate, eggs)
37  0.034395           (french fries, chocolate)
38  0.032129                   (chocolate, milk)
39  0.052660          (mineral water, chocolate)
40  0.039195              (chocolate, spaghetti)
41  0.036395                (french fries, eggs)
42  0.030796                        (eggs, milk)
43  0.050927               (mineral water, eggs)
44  0.036528                   (eggs, spaghetti)
45  0.033729       (mineral water, french fries)
46  0.035729  (mineral water, frozen vegetables)
47  0.031063          (mineral water, green tea)
48  0.040928        (mineral water, ground beef)
49  0.039195            (spaghetti, ground beef)
50  0.047994               (mineral water, milk)
51  0.035462                   (spaghetti, milk)
52  0.033729           (mineral water, pancakes)
53  0.059725          (mineral water, spaghetti)

In [116]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.01) # associate itemsets with confidence over 70%.

            antecedents          consequents  ...  leverage  conviction
0           (chocolate)               (eggs)  ...  0.003751    1.028711
1                (eggs)          (chocolate)  ...  0.003751    1.025603
2        (french fries)          (chocolate)  ...  0.006393    1.046827
3           (chocolate)       (french fries)  ...  0.006393    1.049383
4           (chocolate)               (milk)  ...  0.010898    1.082736
5                (milk)          (chocolate)  ...  0.010898    1.111823
6       (mineral water)          (chocolate)  ...  0.013604    1.073256
7           (chocolate)      (mineral water)  ...  0.013604    1.122357
8           (chocolate)          (spaghetti)  ...  0.010668    1.085581
9           (spaghetti)          (chocolate)  ...  0.010668    1.079070
10       (french fries)               (eggs)  ...  0.005681    1.042232
11               (eggs)       (french fries)  ...  0.005681    1.039640
12               (eggs)               (milk)  ...  0.007509    1.050423
13               (milk)               (eggs)  ...  0.007509    1.076009
14      (mineral water)               (eggs)  ...  0.008090    1.043158
15               (eggs)      (mineral water)  ...  0.008090    1.062815
16               (eggs)          (spaghetti)  ...  0.005239    1.036592
17          (spaghetti)               (eggs)  ...  0.005239    1.038081
18      (mineral water)       (french fries)  ... -0.007011    0.965741
19       (french fries)      (mineral water)  ... -0.007011    0.948894
20      (mineral water)  (frozen vegetables)  ...  0.013007    1.064189
21  (frozen vegetables)      (mineral water)  ...  0.013007    1.218270
22      (mineral water)          (green tea)  ... -0.000430    0.997927
23          (green tea)      (mineral water)  ... -0.000430    0.995748
24      (mineral water)        (ground beef)  ...  0.017507    1.088672
25        (ground beef)      (mineral water)  ...  0.017507    1.305401
26          (spaghetti)        (ground beef)  ...  0.022088    1.163716
27        (ground beef)          (spaghetti)  ...  0.022088    1.373997
28      (mineral water)               (milk)  ...  0.017105    1.089850
29               (milk)      (mineral water)  ...  0.017105    1.209650
30          (spaghetti)               (milk)  ...  0.012900    1.093043
31               (milk)          (spaghetti)  ...  0.012900    1.137061
32      (mineral water)           (pancakes)  ...  0.011071    1.054100
33           (pancakes)      (mineral water)  ...  0.011071    1.180529
34      (mineral water)          (spaghetti)  ...  0.018223    1.102008
35          (spaghetti)      (mineral water)  ...  0.018223    1.159314

[36 rows x 9 columns]

In [115]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="lift",min_threshold=0.1)

            antecedents          consequents  ...  leverage  conviction
0           (chocolate)               (eggs)  ...  0.003751    1.028711
1                (eggs)          (chocolate)  ...  0.003751    1.025603
2        (french fries)          (chocolate)  ...  0.006393    1.046827
3           (chocolate)       (french fries)  ...  0.006393    1.049383
4           (chocolate)               (milk)  ...  0.010898    1.082736
5                (milk)          (chocolate)  ...  0.010898    1.111823
6       (mineral water)          (chocolate)  ...  0.013604    1.073256
7           (chocolate)      (mineral water)  ...  0.013604    1.122357
8           (chocolate)          (spaghetti)  ...  0.010668    1.085581
9           (spaghetti)          (chocolate)  ...  0.010668    1.079070
10       (french fries)               (eggs)  ...  0.005681    1.042232
11               (eggs)       (french fries)  ...  0.005681    1.039640
12               (eggs)               (milk)  ...  0.007509    1.050423
13               (milk)               (eggs)  ...  0.007509    1.076009
14      (mineral water)               (eggs)  ...  0.008090    1.043158
15               (eggs)      (mineral water)  ...  0.008090    1.062815
16               (eggs)          (spaghetti)  ...  0.005239    1.036592
17          (spaghetti)               (eggs)  ...  0.005239    1.038081
18      (mineral water)       (french fries)  ... -0.007011    0.965741
19       (french fries)      (mineral water)  ... -0.007011    0.948894
20      (mineral water)  (frozen vegetables)  ...  0.013007    1.064189
21  (frozen vegetables)      (mineral water)  ...  0.013007    1.218270
22      (mineral water)          (green tea)  ... -0.000430    0.997927
23          (green tea)      (mineral water)  ... -0.000430    0.995748
24      (mineral water)        (ground beef)  ...  0.017507    1.088672
25        (ground beef)      (mineral water)  ...  0.017507    1.305401
26          (spaghetti)        (ground beef)  ...  0.022088    1.163716
27        (ground beef)          (spaghetti)  ...  0.022088    1.373997
28      (mineral water)               (milk)  ...  0.017105    1.089850
29               (milk)      (mineral water)  ...  0.017105    1.209650
30          (spaghetti)               (milk)  ...  0.012900    1.093043
31               (milk)          (spaghetti)  ...  0.012900    1.137061
32      (mineral water)           (pancakes)  ...  0.011071    1.054100
33           (pancakes)      (mineral water)  ...  0.011071    1.180529
34      (mineral water)          (spaghetti)  ...  0.018223    1.102008
35          (spaghetti)      (mineral water)  ...  0.018223    1.159314

[36 rows x 9 columns]